---
name: Build All

on:
  workflow_dispatch:
  push:
    paths:
      - build_matrix.json

jobs:
  discover:
    name: Discover build matrix from json file
    runs-on: ubuntu-latest
    outputs:
      latest_tag: ${{ steps.discover.outputs.latest_tag }}
      build_matrix: ${{ steps.discover.outputs.build_matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: discover
        run: |
          echo "latest_tag=$(jq -r '.["latest_tag"]' variants.json)" | tee -a "$GITHUB_OUTPUT"
          echo "build_matrix=$(jq -r '. | tostring' build_matrix.json)" | tee -a "$GITHUB_OUTPUT"

  build:
    name: Build and push image (${{ matrix.python_version }}, ${{ matrix.base_image_repo }}, ${{ matrix.base_image_tag }})
    needs: discover
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.discover.outputs.build_matrix) }}
    steps:
      - uses: actions/checkout@v4
      - name: Build image and push to Docker Hub
        uses: ./.github/actions/build
        with:
          docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker_token: ${{ secrets.DOCKERHUB_TOKEN }}
          docker_repo: ndunnett/python
          base_image_repo: ${{ matrix.base_image_repo }}
          base_image_tag: ${{ matrix.base_image_tag }}
          python_version: ${{ matrix.python_version }}
          latest_tag: ${{ needs.discover.outputs.latest_tag }}
