---
name: Docker Image CI

on:
  workflow_dispatch:
  push:
    paths:
      - "Dockerfile"

env:
  LATEST_TAG: "jammy-3.12"
  REPO: "ndunnett/python"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.13.0a6", "3.12.3", "3.11.9", "3.10.14"]
        base_image: ["ubuntu"]
        base_image_tag: ["jammy"]
    steps:

      - uses: actions/checkout@v4

      - name: Generate tag
        run: echo "TAG=${{ matrix.base_image_tag }}-$(echo ${{ matrix.python }} | cut -d '.' -f 1,2)" >> "$GITHUB_ENV"

      - name: Build image
        run: |
          set -eux
          docker build . --tag "$REPO:$TAG" \
            --build-arg "PYTHON_VERSION=${{ matrix.python }}" \
            --build-arg "BASE_IMAGE=${{ matrix.base_image }}" \
            --build-arg "BASE_IMAGE_TAG=${{ matrix.base_image_tag }}" \

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push and tag images
        run: |
          set -eux
          docker push "$REPO:$TAG"
          if [ "$TAG" = "$LATEST_TAG" ]; then
            docker manifest create "$REPO:latest" "$REPO:$TAG"
            docker manifest push "$REPO:latest"
          fi
