---
name: Docker Image CI

on:
  workflow_dispatch:
  push:
    paths:
      - "Dockerfile"

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}
    steps:
      - id: generate-matrix
        run: echo "::set-output name=matrix::$(cat build_matrix.json)"

  build:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.generate-matrix.outputs.matrix) }}
    steps:

      - uses: actions/checkout@v4

      - uses: ./.github/actions/build
        with:
          docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker_token: ${{ secrets.DOCKERHUB_TOKEN }}
          docker_repo: "ndunnett/python"
          base_image_repo: ${{ matrix.base_image_repo }}
          base_image_tag: ${{ matrix.base_image_tag }}
          python_version: ${{ matrix.python_version }}
          latest_tag: ${{ matrix.latest_tag }}
