---
name: Docker Image CI

on:
  workflow_dispatch:
  push:
    paths:
      - "Dockerfile"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.13.0b3", "3.12.4", "3.11.9", "3.10.14"]
        base_image_repo: ["ubuntu"]
        base_image_tag: ["noble"]
    steps:

      - uses: actions/checkout@v4

      - uses: ./.github/actions/build
        with:
          docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker_token: ${{ secrets.DOCKERHUB_TOKEN }}
          docker_repo: "ndunnett/python"
          base_image_repo: ${{ matrix.base_image_repo }}
          base_image_tag: ${{ matrix.base_image_tag }}
          latest_tag: "noble-3.12"
