---
name: Docker Image CI

on:
  workflow_dispatch:
  push:
    paths:
      - "Dockerfile"
      - "build_matrix.json"

jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      build_matrix: ${{ steps.discover.outputs.build_matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: discover
        run: |
          echo "build_matrix=$(jq -r '. | tostring' build_matrix.json)" >> "$GITHUB_OUTPUT"

  build:
    needs: discover
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.discover.outputs.build_matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
        with:
          docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker_token: ${{ secrets.DOCKERHUB_TOKEN }}
          docker_repo: "ndunnett/python"
          base_image_repo: ${{ matrix.base_image_repo }}
          base_image_tag: ${{ matrix.base_image_tag }}
          python_version: ${{ matrix.python_version }}
          latest_tag: ${{ matrix.latest_tag }}
