---
name: Docker Image CI

on:
  workflow_dispatch:
  push:
    paths:
      - "Dockerfile"

env:
  LATEST_TAG: "jammy-3.12"
  REPO: "ndunnett/python"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ubuntu: ["jammy"]
        python: ["3.13.0a3", "3.12.2", "3.11.8", "3.10.13"]
    steps:

      - uses: actions/checkout@v4

      - name: Generate tag
        run: echo "TAG=${{ matrix.ubuntu }}-$(echo ${{ matrix.python }} | cut -d '.' -f 1,2)" >> "$GITHUB_ENV"

      - name: Build unflattened image
        run: |
          set -eux
          docker build . --tag "$REPO:$TAG-unflattened" \
            --build-arg "PYTHON_VERSION=${{ matrix.python }}" \
            --build-arg "UBUNTU_TAG=${{ matrix.ubuntu }}"

      - name: Flatten image
        run: |
          set -eux
          docker run --name "ndunnett-python-$TAG" "$REPO:$TAG-unflattened"
          docker export "ndunnett-python-$TAG" | docker import - "$REPO:$TAG"
          docker stop "ndunnett-python-$TAG" && docker remove "ndunnett-python-$TAG"

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push and tag images
        run: |
          set -eux
          docker push "$REPO:$TAG-unflattened"
          docker push "$REPO:$TAG"
          if [ "$TAG" = "$LATEST_TAG" ]; then
            docker manifest create "$REPO:latest" "$REPO:$TAG"
            docker manifest push "$REPO:latest"
          fi
