---
name: Update Build Matrix

on:
  workflow_dispatch:
  push:
    paths:
      - Dockerfile
      - variants.json
  schedule:
    - cron: "0 8 * * 0"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate matrix
        run: python3 ./.github/workflows/scripts/generate_matrix.py -i variants.json -o build_matrix.json

      - name: Commit and push matrix
        run: |
          git config --global user.email "matrix-bot@example.com"
          git config --global user.name "matrix-bot"
          git commit -am "Updated build_matrix.json" && git push || exit 0
